trigger:
  branches:
    include: ["master"]
  paths:
    exclude: ["*.md"]

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight (UTC) RichNav indexer run
  branches:
    include:
    - master

jobs:
- job: RichCodeNav_Indexing
  pool:
    name: Hosted Windows 2019 with VS2019
  variables:
    EnableRichCodeNavigation: true
  timeoutInMinutes: 200

  steps:
    - script: eng/cibuild.cmd -configuration Debug -prepareMachine
      displayName: Build

    - task: RichCodeNavIndexer@0
      displayName: RichCodeNav Upload
      inputs:
        languages: 'csharp'
        environment: production
        richNavLogOutputDirectory: $(Build.SourcesDirectory)/artifacts/bin
      continueOnError: true
      env:
        DOTNET_ROOT: $(Build.SourcesDirectory)/.dotnet
